package model;

public enum MenuOption {
    EXIT,
    REGISTER_PLAYER,
    REGISTER_TREASURE,
    REGISTER_ENEMY,
    REGISTER_ENEMY_TO_LEVEL,
    REGISTER_TREASURE_TO_LEVEL,
    MODIFY_PLAYER_SCORE,
    INCREASE_PLAYER_LEVEL,
    PRINT_LEVEL_OBJECTS,
    COUNT_TREASURE_NAME,
    COUNT_ENEMY_TYPE,
    CHECK_MOST_REPEATED_TREASURE,
    CHECK_MOST_VALUABLE_ENEMY,
    COUNT_ENEMY_CONSONANTS,
    PRINT_USER_TOP_5,
}
